name: graficos
description: Estudo para implementação de API de desenho e renderização de graficos 2D raster (Bitmap)
version: 1.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  glfw: ^0.2.4
  pedantic: ^1.0.0
  ffi_utils: ^0.1.1
  ffi: ^0.1.3
  opengl: ^0.3.4
